"""empty message

Revision ID: d017118df61d
Revises: b2ddb70c1241
Create Date: 2024-05-30 16:43:59.313355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd017118df61d'
down_revision = 'b2ddb70c1241'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('restaurant_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_restaurant_pizzas_res_id_restaurants', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), 'restaurants', ['restaurant_id'], ['id'])
        batch_op.drop_column('res_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('res_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_restaurant_pizzas_restaurant_id_restaurants'), type_='foreignkey')
        batch_op.create_foreign_key('fk_restaurant_pizzas_res_id_restaurants', 'restaurants', ['res_id'], ['id'])
        batch_op.drop_column('restaurant_id')

    # ### end Alembic commands ###
